baseURL = "https://topher1120.github.io"
languageCode = "en-us"
title = "Catastrophic Failures"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
	background_color_class = "bg-purple"

[module]
	[[module.imports]]
	  path = "github.com/theNewDynamic/gohugo-theme-ananke"